### ISSUE TITLE
Bearer Token as a variable does not work

### ISSUE THREAD

**Issue by sviatcraft** [Ganesan-Chandran/vscode-fetch-client#4] opened 2022-06-17 08:59 UTC
**Describe the bug**
Bearer Token as a variable does not work

**To Reproduce**
1. Go to the "Variable" tab
2. Create variable "token"
3. Add token key to that variable
4. Go to "Collection" and create a request
5. In "Request"->"Authorization"->"Bearer Token"->"Token"(field) add `{{token}}`
6. Variable is highlighted in green (is legit)

**Expected behavior**
The request is successful, the token is legit

**Actual behavior**
The request is failing, the token is not legit

**Note**
Token is 100 characters long.
If I paste token-key directly, without variable, it works.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Fetch Client Version 1.1.0
 - VS Code Version 1.69.0-insiders

**Comment by Ganesan-Chandran** [comment] 2022-06-17 13:36
Hi @sviatcraft ,

It is working for me.

1) I have created below variable (test).

![image](https://user-images.githubusercontent.com/14222592/174308409-d450b454-bee5-4ff1-94ed-8fe8b04d02b0.png)

2) I have created one collection, added request to it and attached the variable to collection.

![image](https://user-images.githubusercontent.com/14222592/174308778-6c5eee5d-8d8d-49f7-bfbe-f2417f0c43bc.png)


3) I have added {{token}} in auth bearer token section (my token length is 65).

![image](https://user-images.githubusercontent.com/14222592/174308741-bd289879-575d-4cb1-8e85-04998c0c7f0d.png)

4) I can send the request without fail.

![image](https://user-images.githubusercontent.com/14222592/174308849-3d8ff25f-5ee5-417d-b516-2b28bac1a31c.png)

I couldn't reproduce issue.

Am i missed any steps?

**Comment by sviatcraft** [comment] 2022-06-21 12:02
@Ganesan-Chandran I found out why I am having this problem.
My token in reality is 942 characters long, and I can enter only 100 characters in variables.
Is it possible to increase the max length for variables?

**Comment by Ganesan-Chandran** [comment] 2022-06-21 15:25
Sure @sviatcraft . We will fix this issue in coming release.

**Comment by Ganesan-Chandran** [comment] 2022-07-08 10:14
Removed Max Length restriction. Released in [v1.2.0](https://github.com/Ganesan-Chandran/vscode-fetch-client/releases/tag/v1.2.0). Please update the Fetch Client and let me know your feedback. Thanks.

**Closed as completed by Ganesan-Chandran** 2022-07-08 10:14 UTC
Labels: bug
